import os
import webbrowser


def generate_html_report(
    final_status,
    trust_score,
    reasons,
    generated_report,
    report_language
):
    file_path = "final_audit_report.html"

    if not reasons:
        if report_language == "Hindi":
            reasons = ["कोई प्रमुख समस्या नहीं मिली"]
        else:
            reasons = ["No major issue detected"]

    reasons_html = ""
    for reason in reasons:
        reasons_html += f"<li>{reason}</li>"

    # Convert final status to Hindi
    if report_language == "Hindi":
        status_map = {
            "Successfully Verified Plantation": "सफलतापूर्वक सत्यापित वृक्षारोपण",
            "Genuine Failure": "वास्तविक विफलता",
            "Suspicious Failure Reason": "संदिग्ध विफलता",
            "Likely Fake Plantation": "संभावित फर्जी वृक्षारोपण"
        }

        final_status_hindi = status_map.get(
            final_status,
            final_status
        )
    else:
        final_status_hindi = final_status

    title = "GreenProof AI - Final Plantation Audit Report"
    subject = "Plantation Verification and Final Administrative Report"
    status_label = "Final Plantation Status"
    score_label = "Final Trust Score"
    reason_label = "Key Verification Points"
    report_label = "AI Generated Final Analysis"

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">

        <style>
            body {{
                font-family: Arial, sans-serif;
                padding: 40px;
                line-height: 1.8;
                font-size: 15px;
                background: white;
                color: #222;
            }}

            h1 {{
                text-align: center;
                margin-bottom: 30px;
            }}

            .report-box {{
                margin-top: 20px;
                padding: 20px;
                border: 1px solid #cccccc;
                border-radius: 8px;
                background: #f8f8f8;
            }}

            .footer {{
                margin-top: 40px;
                font-weight: bold;
            }}
        </style>
    </head>

    <body>

        <h1>{title}</h1>

        <p><b>Subject:</b> {subject}</p>
        <p><b>{status_label}:</b> {final_status_hindi}</p>
        <p><b>{score_label}:</b> {trust_score}/100</p>

        <p><b>{reason_label}:</b></p>
        <ul>
            {reasons_html}
        </ul>

        <div class="report-box">
            <p><b>{report_label}:</b></p>
            <p style="white-space: pre-line;">{generated_report}</p>
        </div>

        <div class="footer">
            Generated by GreenProof AI System
        </div>

    </body>
    </html>
    """

    with open(file_path, "w", encoding="utf-8") as file:
        file.write(html_content)

    full_path = os.path.abspath(file_path)
    webbrowser.open("file://" + full_path)

    return file_path