# report_generator.py

import os
import pdfkit


def generate_pdf_report(
    final_status,
    trust_score,
    reasons,
    generated_report,
    report_language
):
    """
    Final Stable Hindi + English PDF Generator
    Uses:
    - Local Hindi Font File
    - wkhtmltopdf
    - Proper Unicode Rendering
    """

    file_path = "final_audit_report.pdf"

    # -----------------------------------
    # Default Reasons
    # -----------------------------------
    if not reasons:
        if report_language == "Hindi":
            reasons = ["कोई प्रमुख समस्या नहीं मिली"]
        else:
            reasons = ["No major issue detected"]

    reasons_html = ""
    for reason in reasons:
        reasons_html += f"<li>{reason}</li>"

    # -----------------------------------
    # Language-based labels
    # -----------------------------------
    if report_language == "Hindi":
        title = "ग्रीनप्रूफ एआई - अंतिम वृक्षारोपण ऑडिट रिपोर्ट"
        subject = "वृक्षारोपण सत्यापन एवं अंतिम प्रशासनिक रिपोर्ट"
        status_label = "अंतिम वृक्षारोपण स्थिति"
        score_label = "अंतिम ट्रस्ट स्कोर"
        reason_label = "मुख्य सत्यापन बिंदु"
        report_label = "एआई द्वारा तैयार अंतिम विश्लेषण"

    else:
        title = "GreenProof AI - Final Plantation Audit Report"
        subject = "Plantation Verification and Final Administrative Report"
        status_label = "Final Plantation Status"
        score_label = "Final Trust Score"
        reason_label = "Key Verification Points"
        report_label = "AI Generated Final Analysis"

    # -----------------------------------
    # Local Hindi Font Path (IMPORTANT)
    # -----------------------------------
    font_path = os.path.abspath(
        "fonts/NotoSansDevanagari-Regular.ttf"
    ).replace("\\", "/")

    # -----------------------------------
    # HTML Content
    # -----------------------------------
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">

        <style>

            @font-face {{
                font-family: HindiFont;
                src: url("file:///{font_path}");
            }}

            body {{
                font-family: HindiFont;
                padding: 30px;
                line-height: 1.8;
                font-size: 14px;
            }}

            h1 {{
                text-align: center;
                margin-bottom: 20px;
            }}

            p {{
                margin-bottom: 10px;
            }}

            ul {{
                margin-left: 20px;
            }}

            .report-box {{
                margin-top: 20px;
                padding: 15px;
                border: 1px solid #cccccc;
                border-radius: 8px;
                background: #f8f8f8;
            }}

            .footer {{
                margin-top: 30px;
                font-weight: bold;
            }}

            @page {{
                size: A4;
                margin: 2cm;
            }}

        </style>
    </head>

    <body>

        <h1>{title}</h1>

        <p><b>Subject:</b> {subject}</p>

        <p><b>{status_label}:</b> {final_status}</p>

        <p><b>{score_label}:</b> {trust_score}/100</p>

        <p><b>{reason_label}:</b></p>

        <ul>
            {reasons_html}
        </ul>

        <div class="report-box">
            <p><b>{report_label}:</b></p>
            <p>{generated_report}</p>
        </div>

        <div class="footer">
            Generated by GreenProof AI System
        </div>

    </body>
    </html>
    """

    # -----------------------------------
    # wkhtmltopdf Configuration
    # -----------------------------------
    config = pdfkit.configuration(
        wkhtmltopdf=r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"
    )

    options = {
        "encoding": "UTF-8",
        "enable-local-file-access": "",
        "quiet": ""
    }

    # -----------------------------------
    # Generate PDF
    # -----------------------------------
    pdfkit.from_string(
        html_content,
        file_path,
        configuration=config,
        options=options
    )

    return file_path